name: celestial_navigation
description: Celestial Navigation App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.4
  path_provider: ^2.1.1
  path: ^1.8.3
  sensors_plus: ^3.0.0
  http: ^1.4.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true